kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: node-k8s-config-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-k8s-config-example
    spec:
      containers:
        - name: node-k8s-config-example-container
          image: joshes/node-k8s-config-example:1.0.0
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          ports:
          - containerPort: 3000
          env:
            - name: 'DEBUG'
              value: 'k8s-config'
      volumes:
        - name: config-volume
          configMap:
            name: special-config
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
