kind: Service
apiVersion: v1
metadata:
  name: node-k8s-config-example
spec:
  selector:
    app: node-k8s-config-example-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
